version: 0.2

env:
  parameter-store:
    API_URL: "/Prod/DokugakuEngineer/Client/API_URL"
    API_URL_BROWSER: "/Prod/DokugakuEngineer/Client/API_URL_BROWSER"
    AWS_ACCESS_KEY_ID: "/Prod/DokugakuEngineer/Client/AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "/Prod/DokugakuEngineer/Client/AWS_SECRET_ACCESS_KEY"
    AWS_CLIENT_BUCKET_NAME: "/Prod/DokugakuEngineer/Client/AWS_CLIENT_BUCKET_NAME"
    AWS_CLOUDFRONT: "/Prod/DokugakuEngineer/Client/AWS_CLOUDFRONT"
    AWS_DEFAULT_REGION: "/Prod/DokugakuEngineer/Client/AWS_DEFAULT_REGION"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - sudo apt-get update
  pre_build:
    commands:
      - echo 'Start npm install'
      - npm install
  build:
    commands:
      - echo 'Start npm run generate'
      - npm run generate
  post_build:
    commands:
      - echo 'Start gulp deploy'
      - ./node_modules/.bin/gulp deploy
