version: "3"

services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www
    depends_on:
      - api

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - ./docker/db/db-variables.env

  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www
    depends_on:
      - db
