version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "3333:3333"
      - "8081:8081"
    volumes:
      - ./client:/var/www
      - /var/www/node_modules/
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
      - "20022:20022"
    volumes:
      - ./api:/var/www
      - phpsocket:/var/run
    depends_on:
      - api
    entrypoint:
      - sh
      - /var/www/nginx-docker-entrypoint.sh

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    entrypoint:
      - sh
      - /var/www/docker-entrypoint.sh
    ports:
      - "22:22"
    volumes:
      - ./api:/var/www
      - /var/www/vendor/
      - phpsocket:/var/run
    environment:
      - APP_ENV=development
    depends_on:
      - db

  db:
    image: mysql:5.7.12
    ports:
      - "3306:3306"
    env_file:
      - ./docker/db/db-variables.env

volumes:
  phpsocket:
