version: "3"

services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/dokugaku-engineer-blog
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/dokugaku-engineer-blog
    depends_on:
      - db
