version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/var/www
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - ./docker/db/db-variables.env
